#!/bin/sh
#
# GPG script to decrypt a file with our typical settings.
#
# Example:
#
#     $ gpg-decrypt example.txt.gpg
#     (prompt for password)
#     #=> example.txt.gpg
#
# To get our settings, we use these gpg options:
#
#    --quiet                       Try to be as quiet as possible.
#    --no-greeting                 Suppress the initial copyright message but do not enter batch mode.
#
# If you are on an older system, then you may want to add this:
#
#    --no-use-agent                Do not use a system agent such as Ubuntu's gnome-keyring process.
#
#
# ## See also
# 
# These commands are similar:
# 
#   * [`gpg-encrypt`](https://github.com/SixArm/gpg-encrypt): 
#     use GPG to encrypt a file using our best settings.
#   
#   * [`gpg-decrypt`](https://github.com/SixArm/gpg-decrypt): 
#     use GPG to decrypt a file using our best settings.
#
#   * [`openssl-encrypt`](https://github.com/SixArm/openssl-encrypt): 
#     use OpenSLL to encrypt a file using our best settings.
#   
#   * [`openssl-decrypt`](https://github.com/SixArm/openssl-decrypt): 
#     use OpenSSL to decrypt a file using our best settings.
# 
#
# ## Tracking
#
#   * Command: gpg-decrypt
#   * Version: 3.0.0
#   * Created: 2010-05-20
#   * Updated: 2017-09-03
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
umask_save=`umask`
umask 0077
gpg --decrypt --quiet --no-greeting  "$@"
umask "$umask_save"
