#!/bin/sh
#
# GPG script to decrypt a file with our typical settings.
#
# Example:
#
#     $ gpg-decrypt example.txt.gpg
#     (prompt for password)
#     #=> example.txt.gpg
#
# To get our settings, we use these gpg options:
#
#    --quiet                       Try to be as quiet as possible.
#    --no-greeting                 Suppress the initial copyright message but do not enter batch mode.
#
# If you are on an older system, then you may want to add this:
#
#    --no-use-agent                Do not use a system agent such as Ubuntu's gnome-keyring process.
#
# Command: gpg-decrypt
# Version: 2.1.0
# Created: 2010-05-20
# Updated: 2017-01-09
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
umask_save=`umask`
umask 0077
gpg --decrypt --quiet --no-greeting  "$@"
umask "$umask_save"
